@startuml

[*] --[#green]> Idle : Start System

state Idle #yellow {

}

state Initialized {
    Idle --> Initialized : DIO
    Initialized --> Initialized : LCD
    Initialized --> Initialized : KEY_PAD  
}

state CreateTask {
    Initialized --> CreateTask : Using FreeRTOS
    Initialized --[#red]> LCD : QueueCreatingError
}

state KeyPadTask #blue{
    CreateTask --> KeyPadTask : High Priority
    KeyPadTask --> LCD : Pressed Key
    KeyPadTask --[#red]> LCD : QueueSendError
    note left of KeyPadTask: Periodicity 100ms 
}

state ChoosePatternTask #blue {
    CreateTask --> ChoosePatternTask : Low Priority
    ChoosePatternTask --[#red]> LCD : QueueReceiveError
    note left of ChoosePatternTask: Periodicity 100ms
    note right of ChoosePatternTask: Low-value key cannot interrupt high-value
}

state Queue {
    KeyPadTask --> Queue : Pressed Key
    Queue --> ChoosePatternTask : Pressed Key
}

state LCD {

}

state Application #green {
    ChoosePatternTask ---[#green]> Application : Desired Pattern
}

@enduml